//! Netscape `cookies.txt` serializer.
//!
//! yt-dlp's `--cookies <file>` flag accepts the Netscape HTTP Cookie
//! File format, which is a tab-separated text file with one cookie per
//! line:
//!
//! ```text
//! # Netscape HTTP Cookie File
//! # https://curl.se/docs/http-cookies.html
//! .youtube.com    TRUE    /    TRUE    1762560000    SID    g.a000xx...
//! ```
//!
//! Columns (tab-separated, in order):
//!   1. domain                — `.example.com` (with leading dot if subdomain-wide)
//!   2. include_subdomains    — "TRUE" if domain starts with `.`, else "FALSE"
//!   3. path                  — usually `/`
//!   4. secure                — "TRUE" if HTTPS-only
//!   5. expires               — unix epoch seconds; 0 for session cookies
//!   6. name
//!   7. value
//!
//! Lines starting with `#` are comments. Blank lines are ignored.
//!
//! The order of cookies in the file does not matter to yt-dlp; we
//! sort by domain then name for deterministic output (helpful when
//! diffing across re-logins to verify the user's session is fresh).

use cookie::Cookie;

/// One cookie entry to serialize. We lift the few fields we need from
/// `tauri::Cookie` (which is a wrapper around the `cookie` crate's
/// `Cookie<'static>`) up here so the serializer can be unit-tested in
/// isolation without needing a Tauri runtime.
#[derive(Debug, Clone)]
pub struct NetscapeCookie {
    pub domain: String,
    pub path: String,
    pub secure: bool,
    /// Unix epoch seconds. None → session cookie (rendered as 0).
    pub expires: Option<i64>,
    pub name: String,
    pub value: String,
}

impl NetscapeCookie {
    /// Build from a `cookie::Cookie` (the underlying type Tauri exposes
    /// via `WebviewWindow::cookies()`). Domain falls back to
    /// `default_domain` when the cookie itself doesn't carry one — this
    /// happens for cookies set without an explicit Domain attribute,
    /// where the browser scopes them to the request host. Caller
    /// supplies that host.
    pub fn from_cookie(c: &Cookie<'static>, default_domain: &str) -> Self {
        let raw_domain = c.domain().unwrap_or("").trim().to_string();
        let domain = if raw_domain.is_empty() {
            // No Domain attr → host-only cookie. yt-dlp accepts these
            // with the bare host (no leading dot).
            default_domain.trim_start_matches('.').to_string()
        } else {
            raw_domain
        };
        let path = c.path().unwrap_or("/").to_string();
        let secure = c.secure().unwrap_or(false);
        let expires = c.expires().and_then(|e| e.datetime()).map(|dt| dt.unix_timestamp());
        NetscapeCookie {
            domain,
            path,
            secure,
            expires,
            name: c.name().to_string(),
            value: c.value().to_string(),
        }
    }
}

/// Serialize a list of cookies into Netscape `cookies.txt` text. Sorts
/// for determinism (helps users / us diff after re-login). Filters out
/// cookies missing a name OR an expired-already timestamp — those are
/// dead weight and would just confuse yt-dlp.
pub fn serialize(cookies: &[NetscapeCookie]) -> String {
    let mut sorted: Vec<&NetscapeCookie> = cookies.iter().collect();
    sorted.sort_by(|a, b| a.domain.cmp(&b.domain).then_with(|| a.name.cmp(&b.name)));

    // Header per spec — yt-dlp doesn't strictly require it but most
    // tools consider the file invalid without the magic comment.
    let mut out = String::from("# Netscape HTTP Cookie File\n");
    out.push_str("# Auto-generated by whatsub in-app YouTube login. Do not edit.\n\n");

    let now_ts = current_unix_seconds();
    for c in sorted {
        if c.name.is_empty() {
            continue;
        }
        let expires = c.expires.unwrap_or(0);
        // Skip cookies that have already expired — they're pointless.
        // Session cookies (expires == 0) are kept; yt-dlp treats 0 as
        // "until the cookie jar is destroyed".
        if expires > 0 && expires < now_ts {
            continue;
        }
        let include_sub = if c.domain.starts_with('.') { "TRUE" } else { "FALSE" };
        let secure = if c.secure { "TRUE" } else { "FALSE" };
        out.push_str(&format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            c.domain, include_sub, c.path, secure, expires, c.name, c.value,
        ));
    }
    out
}

fn current_unix_seconds() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make(domain: &str, name: &str, value: &str, secure: bool, expires: Option<i64>) -> NetscapeCookie {
        NetscapeCookie {
            domain: domain.into(),
            path: "/".into(),
            secure,
            expires,
            name: name.into(),
            value: value.into(),
        }
    }

    #[test]
    fn header_present() {
        let s = serialize(&[]);
        assert!(s.starts_with("# Netscape HTTP Cookie File"));
    }

    #[test]
    fn subdomain_flag_follows_leading_dot() {
        let s = serialize(&[
            make(".youtube.com", "SID", "abc", true, Some(2_000_000_000)),
            make("youtube.com", "HOST_ONLY", "xyz", true, Some(2_000_000_000)),
        ]);
        let lines: Vec<&str> = s.lines().filter(|l| !l.starts_with('#') && !l.is_empty()).collect();
        assert!(lines.iter().any(|l| l.contains(".youtube.com\tTRUE\t")));
        assert!(lines.iter().any(|l| l.contains("youtube.com\tFALSE\t")));
    }

    #[test]
    fn expired_cookies_dropped() {
        let s = serialize(&[
            make(".youtube.com", "FRESH", "v1", true, Some(2_000_000_000)),
            make(".youtube.com", "STALE", "v2", true, Some(1_000_000_000)),  // 2001 — definitely expired
            make(".youtube.com", "SESSION", "v3", true, None),                // session, kept
        ]);
        assert!(s.contains("FRESH"));
        assert!(!s.contains("STALE"));
        assert!(s.contains("SESSION"));
    }

    #[test]
    fn sorted_deterministic() {
        let s1 = serialize(&[
            make(".b.com", "Z", "v", true, Some(2_000_000_000)),
            make(".a.com", "X", "v", true, Some(2_000_000_000)),
            make(".a.com", "Y", "v", true, Some(2_000_000_000)),
        ]);
        // a.com lines should both come before b.com; X before Y within a.com
        let body: Vec<&str> = s1.lines().filter(|l| !l.starts_with('#') && !l.is_empty()).collect();
        assert!(body[0].starts_with(".a.com"));
        assert!(body[0].contains("\tX\t"));
        assert!(body[1].starts_with(".a.com"));
        assert!(body[1].contains("\tY\t"));
        assert!(body[2].starts_with(".b.com"));
    }

    #[test]
    fn session_cookie_renders_zero_expires() {
        let s = serialize(&[make(".youtube.com", "S", "v", true, None)]);
        // Field 5 is expires; check it's "0" for session cookies.
        let line = s.lines().find(|l| l.contains("\tS\t")).unwrap();
        let fields: Vec<&str> = line.split('\t').collect();
        assert_eq!(fields[4], "0");
    }
}
